# Generated by Django 3.2.16 on 2022-10-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_blabla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blabla',
        ),
    ]
